/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.2/userguide/building_java_projects.html
 */

plugins {
    application
    `java-library`
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation("io.vertx:vertx-mqtt:4.2.6")
    implementation("io.vertx:vertx-core:4.2.6")
    implementation("io.vertx:vertx-web:4.2.6")
    implementation("io.vertx:vertx-web-client:4.2.6")
    implementation("com.google.code.gson:gson:2.8.8") //for json
    implementation("io.github.java-native:jssc:2.9.6") //for serial communication
    implementation("org.slf4j:slf4j-api:1.7.32")
    implementation("org.slf4j:slf4j-simple:1.7.32")
    implementation("org.json:json:20210307")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.13.0")
}

application {
    // Define the main class for the application.
    mainClass.set("org.mqttserver.Main")
}

tasks.test {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
