/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.2/userguide/building_java_projects.html
 */

plugins {
    application
    `java-library`
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation("io.vertx:vertx-mqtt:4.5.1") //for mqtt vertx server
    implementation("com.google.code.gson:gson:2.8.8") //for json
    implementation("io.github.java-native:jssc:2.9.6") //for serial communication
}

application {
    // Define the main class for the application.
    mainClass.set("org.mqttserver.Main")
}

tasks.test {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
